import React from "react";
import '../../styles/motivationalPhrase.css';

const Frases = () => {
  const frases = [
    "Cuando creas que no puedes más, haz una repetición extra.",
    "El diálogo interno positivo puede transformar tu rendimiento.",
    "El éxito no es solo físico, es mental y emocional también.",
    "Si no desafías tus límites, no los superarás.",
    "La diferencia entre lo posible y lo imposible está en la determinación de una persona.",
    "La fortaleza mental te llevará a lugares donde el físico no puede.",
    "El dolor es temporal, la gloria es eterna.",
    "No puedes tener un cuerpo fuerte con una mente débil.",
    "Hoy duele, mañana será más fácil.",
    "No te rindas, sufre ahora y vive el resto de tu vida como un campeón.",
    "No es solo lo que haces en el gimnasio, sino también cómo manejas tu mente.",
    "Nunca dudes de tu potencial, eres capaz de grandes cosas.",
    "Cada día es una nueva oportunidad para mejorar.",
    "El cuerpo sigue a la mente, mantén pensamientos positivos.",
    "El dolor que sientes hoy será la fuerza que sientas mañana.",
    "Los campeones siguen jugando hasta que lo hacen bien.",
    "El estrés es el peor enemigo del rendimiento.",
    "El verdadero atleta no es aquel que nunca falla, sino el que nunca se rinde.",
    "El mejor entrenamiento es aquel que también fortalece tu mente.",
    "No esperes a que otros crean en ti, empieza por creer en ti mismo.",
    "Entrena con propósito, compite con pasión.",
    "Lo difícil se hace, lo imposible se intenta.",
    "No tengas miedo de brillar.",
    "Recuerda, el fracaso solo es un peldaño hacia el éxito.",
    "El descanso y la relajación son esenciales para el rendimiento.",
    "El cuerpo logra lo que la mente cree.",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
    "No cuentes los días, haz que los días cuenten.",
    "El cambio empieza en el momento en que crees en ti.",
    "Haz de cada entrenamiento una victoria personal.",
    "No todo se trata de ganar, a veces se trata de aprender.",
    "El progreso es imposible sin cambio, y quienes no pueden cambiar sus mentes no pueden cambiar nada.",
    "El éxito en cualquier cosa siempre comienza con la disciplina.",
    "No tengas miedo de pedir ayuda, eso también es fortaleza.",
    "No te subestimes, eres más capaz de lo que crees.",
    "No esperes a estar motivado para empezar, empieza y la motivación llegará.",
    "Un atleta no puede correr con dinero en sus bolsillos. Debe correr con esperanza en su corazón y sueños en su mente.",
    "No hay límites para quien tiene determinación.",
    "No te castigues por un mal día, aprende de él y sigue adelante.",
    "Eres capaz de lograr más de lo que imaginas.",
    "Los resultados no aparecen de la noche a la mañana, la constancia es la clave.",
    "El descanso es parte del entrenamiento.",
    "No dejes que el miedo decida tu futuro.",
    "No tengas miedo de fallar, ten miedo de no intentarlo.",
    "Tu bienestar emocional es una prioridad, no un lujo.",
    "La mejor inversión que puedes hacer es en ti mismo.",
    "Cuidar tu mente es tan crucial como entrenar tu cuerpo.",
    "La confianza en uno mismo es el primer paso hacia el éxito.",
    "Si no te esfuerzas al máximo, ¿cómo sabrás dónde está tu límite?",
    "Tu único límite es tu mente.",
    "El bienestar mental es tan importante como el físico.",
    "El mundo necesita lo que solo tú puedes ofrecer.",
    "El sudor de hoy es la victoria de mañana.",
    "La salud mental es la base de cualquier éxito duradero.",
    "La seguridad en uno mismo es la clave para cualquier logro.",
    "Rodéate de personas que sumen a tu bienestar.",
    "La mente controla el cuerpo, aprende a entrenarla también.",
    "Nunca es demasiado tarde para ser la mejor versión de ti mismo.",
    "Tu confianza es tu mejor herramienta para alcanzar el éxito.",
    "Cada paso que das te acerca un poco más a tu objetivo.",
    "El equilibrio entre cuerpo y mente es la clave para el éxito.",
    "Tu mente es un músculo, ejercítala con pensamientos positivos.",
    "Cree en ti mismo y todo será posible.",
    "Cada día es una nueva oportunidad para ser mejor.",
    "Eres más fuerte de lo que crees.",
    "Celebra cada pequeño logro, cada paso cuenta.",
    "Cada entrenamiento cuenta, cada repetición te acerca a tu meta.",
    "La ansiedad y la presión no deben definirte.",
    "Si te caes siete veces, levántate ocho.",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
    "No compares tu progreso con el de otros, cada camino es único.",
    "A veces, descansar es la mejor estrategia para avanzar.",
    "Escucha a tu cuerpo y respeta sus tiempos.",
    "Confía en el proceso y en tu capacidad de mejorar.",
    "No te castigues, aprende a escucharte.",
    "Desconectarte de vez en cuando es tan importante como entrenar.",
    "Corre cuando puedas, camina cuando necesites, pero nunca te detengas.",
    "Cada pequeño paso te acerca a tu mejor versión.",
    "El talento gana juegos, pero el trabajo en equipo y la inteligencia ganan campeonatos."
  ];

  const randomFrase = frases[Math.floor(Math.random() * frases.length)];

  return  <p><b>{randomFrase}</b></p>;
};

export default Frases;
