"""empty message

Revision ID: 0e1b245901cc
Revises: a123f98e6460
Create Date: 2025-02-01 11:29:38.096842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1b245901cc'
down_revision = 'a123f98e6460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nick', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['nick'])
        batch_op.create_unique_constraint(None, ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('sex')
        batch_op.drop_column('city')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('user_name')
        batch_op.drop_column('nick')

    # ### end Alembic commands ###
