"""empty message

Revision ID: 15dd13d01a00
Revises: 0e1b245901cc
Create Date: 2025-02-03 08:03:51.405791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dd13d01a00'
down_revision = '0e1b245901cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_nick_key', type_='unique')
        batch_op.drop_column('nick')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nick', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_nick_key', ['nick'])

    # ### end Alembic commands ###
