"""empty message

Revision ID: 41fea90c03e4
Revises: af7f4563e60a
Create Date: 2025-02-08 11:54:36.988190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fea90c03e4'
down_revision = 'af7f4563e60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'workout', ['workout_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workout_id')

    # ### end Alembic commands ###
