"""empty message

Revision ID: b968bb0b477d
Revises: ed747e7a9f05
Create Date: 2025-02-17 14:46:34.229756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b968bb0b477d'
down_revision = 'ed747e7a9f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
