"""empty message

Revision ID: c3507ab9ee32
Revises: 41fea90c03e4
Create Date: 2025-02-08 12:10:59.272739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3507ab9ee32'
down_revision = '41fea90c03e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('duration')

    with op.batch_alter_table('workout_completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_mood', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_completion', schema=None) as batch_op:
        batch_op.drop_column('description_mood')

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
