"""empty message

Revision ID: f7b60586cff3
Revises: b67d399e158f
Create Date: 2025-02-08 15:03:27.304425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b60586cff3'
down_revision = 'b67d399e158f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_per_week', sa.Integer(), nullable=False))

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routine_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'routine', ['routine_id'], ['id'])
        batch_op.drop_column('days_per_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_per_week', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('routine_id')

    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_column('days_per_week')

    # ### end Alembic commands ###
